server:
  port: 8085
spring:
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
bycg:
  jwt:
    secret: bycg@Login(Auth}*^31)&bycg% # 登录校验的密钥
    pubKeyPath: D:\\bycg\\rsa\\rsa.pub # 公钥地址
    priKeyPath: D:\\bycg\\rsa\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: BYCG_TOKEN
